### ISSUE TITLE
Feature request: equal axis scaling

### ISSUE THREAD

**Issue by llvs** [facontidavide/PlotJuggler#118] opened 2018-10-26 13:09 UTC
Dear Davide,

Here comes another feature request:
When using a custom x-axis (dragged with the right mouse button), I can create an x,y position plot which is very nice. However, it would be very useful to have an option for a locked axis ratio such that, e.g. right angles, appear as such in the plot. Like with the Matlab command "axis equal".

Best regards

**Comment by facontidavide** [comment] 2018-10-26 20:17
It would be a nice feature to have. I will probably implement it at some point

**Comment by facontidavide** [comment] 2019-02-06 18:14
From a UI point of view, I am not sure how and where this feature should be toggled... Suggestions?

**Comment by koenlek** [comment] 2019-03-01 02:24
@llvs great suggestion! We would really like this feature too. 

@facontidavide: How about in the right-click menu on the plot? 

How about adding it to the zoom related section, the new section would become:
- Edit X-axis limits (gray out or hide in case not in x/y plot mode)
- Edit Y-axis limits
- Set X/Y scale equal (gray out or hide in case not in x/y plot mode)
- Zoom out
- Zoom out horizontally
- Zoom out vertically 

I checked and both matplotlib and matlab use 'equal' as the terminology for such axis scaling. 'square' instead forces the plot to be square in size (the canvas of the plot, so to say). 

By the way: In the suggestion above I sneaked an extra feature request in: allow setting the X axis limits for X/Y plots. I see that this was already requested in #110. Setting both X/Y axis limits manually actually can break an equal scale. In equal scale mode, I'd just find the square that fits both the chosen x limits and y limits. I.e. take `axis_padding = max(ymax-ymin,xmax-xmin)/2` and if y interval is larger, do `xmin_new = xmin - axis_padding` and `xmax_new = xmax + axis_padding`, if x interval is larger, same idea but sway x/y varnames.

**Comment by skohlbr** [comment] 2019-03-12 20:11
Just tried the XY plot functionality, and this was the first thing that I immediately looked for in the UI after seeing the nice (but off axis ratio) plot. So another vote for this. For most XY data this would be the preferred default methinks.

**Comment by facontidavide** [comment] 2019-03-23 12:23
started working on this feature... It is more hard that I initially estimated :(

**Comment by facontidavide** [comment] 2019-03-24 13:55
I can proudly announce that the "equal axis scaling" as been merged.

There is a fairly high possibility that I broke something in the process, so: "if you see something, say something".

Cheers

**Comment by llvs** [comment] 2019-03-25 08:34
Thanks a lot! Will try it immediately.

**Comment by aeudes** [comment] 2019-03-25 09:36
Cool, it's still just amazing the pace at which this tool evolved !
Very quick testing show strange behaviour with zoom when equal axis is activated, it could be replicated in a graph with angular_velocity.x/y from imu in tilt_laser.bag:
- when using window zoom, sometimes, making successive zoom produce a zoom out
- using mouse wheel zoom makes zoom out unpredictably.
- sometimes, I loose the ability to make a zoom window (click + move did not draw the rectangle, but I see the icon changed)
- i don't known what should be the behaviour of wheel on axis with this mode activated.

**Comment by facontidavide** [comment] 2019-03-25 09:42
Can you share a video (screencast) of the behavior you consider "weird"?

- About "mouse wheel on axis", that will break the __equal ratio__, so, I need to disable it.

- "sometimes, I loose the ability to make a zoom window" this happened to me as well. I am not able to reproduce it unfortunately, I need to fix this!

**Comment by aeudes** [comment] 2019-03-25 12:31
1/ continuous track-pad zoom
2/ 2 successive window zoom

![zoom_error](https://user-images.githubusercontent.com/462068/54919845-15748f00-4f02-11e9-8d99-d2b483ca1bcb.gif)

**Comment by facontidavide** [comment] 2019-03-25 12:53
can you share the rosbag please?

**Comment by facontidavide** [comment] 2019-03-25 13:53
I just pushed a commit that might help.

**Comment by aeudes** [comment] 2019-03-25 15:14
I have used: the sample data with angular_velocity.x/y from imu topic  tilt_laser.bag.

**Comment by facontidavide** [comment] 2019-03-25 15:24
Check the last version

**Comment by aeudes** [comment] 2019-03-25 16:15
With last version both the zoom error seems to be fixed !

I still trigger the "loose the ability to make a zoom window" :
- if you zoom windows to have one point or less.
- zoom out with mouse wheel to maximum
-> loose the zoom window
- zoom in with the wheel, at some point recover the zoom window

**Comment by facontidavide** [comment] 2019-03-25 17:18
fixed... hopefully :)

**Comment by aeudes** [comment] 2019-03-25 17:35
Look like fixed here also !

**Comment by facontidavide** [comment] 2019-03-25 19:14
I refactored this feature to remove some complexity. It should still work fine

**Closed by facontidavide** 2019-03-25 19:14 UTC
Labels: enhancement

**Comment by skohlbr** [comment] 2019-03-25 19:52
XY plots have correct aspect ratio per default now, which is awesome. :)
Unfortunately, the separate axis scaling from #135 (X or Y key + mouse wheel) doesn't work anymore (in any plot, not just XY) after updating to latest master.

**Comment by facontidavide** [comment] 2019-03-25 20:34
Check the cheatsheet. There is a new way to do single axis scaling
