### ISSUE TITLE
0x000007b | Application error | Build error | windows

### ISSUE THREAD

**Issue by harish1992mech** [facontidavide/PlotJuggler#452] opened 2021-06-04 18:27 UTC
Hi Davide,

I am getting the below error while trying to start the PlotJuggler application which was built in a windows 10 environment

![image](https://user-images.githubusercontent.com/21367945/120844823-97a27880-c58d-11eb-981a-fca133ce45f1.png)

# Steps to reproduce
- Built the software in Windows 10 using mingw32-make command, with the make file created using the win32build.bat. I am a newbie in C++ application development so I suspect some basic issues with my build environment, but I couldn't find the solution from internet. Initially after building the software, I got the below errors, but I copied the files from the Qt installation directory. The errors were gone but I got the error mentioned above.

![image](https://user-images.githubusercontent.com/21367945/120845268-329b5280-c58e-11eb-8481-824316ebdd64.png)

![image](https://user-images.githubusercontent.com/21367945/120846270-7f335d80-c58f-11eb-906a-a64e93976ba5.png)

I've tried running the dependency walker and below is a screenshot (I am not sure if this will help in any way)

![image](https://user-images.githubusercontent.com/21367945/120846546-e6e9a880-c58f-11eb-87c1-d101991bd007.png)

Could you kindly help me in getting this issue resolved.

Regards,
Harish

**Comment by facontidavide** [comment] 2021-06-09 07:36
The problem is that it can't find the Qt libraries.

All the information you need is here. https://wiki.qt.io/Deploy_an_Application_on_Windows

I am closing this issue because it is not related to PlotJuggler, but is instead related to Qt in general.

**Closed by facontidavide** 2021-06-09 07:36 UTC
