### ISSUE TITLE
[ROS/noetic Bug] Lag on plot

### ISSUE THREAD

**Issue by Julien-Livet** [facontidavide/PlotJuggler#536] opened 2021-10-06 14:09 UTC
I discovered and used this amazing tool on recent robotic projects with ROS/melodic (on VM) !

# Problem description

I try it on ROS/noetic after ROS/melodic and I observe a "lag" on plots with ROS topic (I reproduce the problem with PJ default data).

![image](https://user-images.githubusercontent.com/76999467/136217794-0536c5e9-c6ac-481d-a91c-8e2ae40f4c93.png)

# Steps to reproduce (important)

- Platform / Operative System: Xubuntu 20.04 / ROS noetic (on VM with VirtualBox)
- rosrun plotjuggler plotjuggler -t
- Select "Dummy Streamer" and plot "data_vect/0"
- Play (and pause) to observe lag

**Comment by facontidavide** [comment] 2021-10-06 14:15
Duplicate of #530 

![image](https://user-images.githubusercontent.com/2822888/136220465-7276a10f-ad9a-4bce-97df-426a2644a816.png)

Disable OpenGL as described here: https://github.com/facontidavide/PlotJuggler/issues/530

**Closed by facontidavide** 2021-10-06 14:15 UTC

**Comment by Julien-Livet** [comment] 2021-10-06 14:37
Thanks!
Sorry for duplication, I only saw open issues --'...
