### ISSUE TITLE
Plot Jugger 3.10 on Windows 10 still problems reading log file

### ISSUE THREAD

**Issue by davidemiccone** [facontidavide/PlotJuggler#419] opened 2021-03-25 08:33 UTC
I attacched a ulg file that give me error "bad allocation" under Windows 10.

Any change to resolve?

Davide.

[09_01_28.zip](https://github.com/facontidavide/PlotJuggler/files/6203159/09_01_28.zip)

**Comment by facontidavide** [comment] 2021-04-01 09:23
Sorry to hear that. Unfortunately I have very little time to maintain ULog for the time being. I hope I will find some bandwidth in the future

**Comment by dgeorge83616** [comment] 2021-04-15 23:26
@davidemiccone, did you rebuild with this: https://github.com/facontidavide/PlotJuggler/commit/9505f51544518483d24e31ca9ea9135fa579fac1

**Comment by facontidavide** [comment] 2021-05-18 20:46
I just tried with the latest version and it work. Can you try version 3.1.1 that I released yesterday?

**Comment by facontidavide** [comment] 2021-05-20 16:11
Since I can not reproduce the issue with the given file, I am going to close this as "solved"

**Closed by facontidavide** 2021-05-20 16:11 UTC
Labels: bug

**Comment by facontidavide** [comment] 2021-06-12 14:01
Fixed
